name: Test

on:
  push:

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        swift:
          - "5.3"
          - "5.4"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: fwal/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v2
      - name: Resolve packages
        run: swift package resolve
      - name: Build
        run: swift build --enable-test-discovery
      - name: Run tests
        run: swift test --enable-test-discovery
